<?php

namespace ContainerUcStKKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FPgZsSkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FPgZsSk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FPgZsSk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activity' => ['privates', '.errored..service_locator.FPgZsSk.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.FPgZsSk": it references class "App\\Entity\\Activity" but no such service exists.'],
            'markdown' => ['privates', 'cebe\\markdown\\Markdown', 'getMarkdownService', true],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'markdown' => 'cebe\\markdown\\Markdown',
        ]);
    }
}
