<?php

namespace ContainerUcStKKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkdownService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'cebe\markdown\Markdown' shared autowired service.
     *
     * @return \cebe\markdown\Markdown
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/Parser.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/block/CodeTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/block/HeadlineTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/block/HtmlTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/block/ListTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/block/QuoteTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/block/RuleTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/inline/CodeTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/inline/EmphStrongTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/inline/LinkTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/cebe/markdown/Markdown.php';

        return $container->privates['cebe\\markdown\\Markdown'] = new \cebe\markdown\Markdown();
    }
}
