<?php

namespace ContainerLHUNU3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I0Iy2AvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I0Iy2Av' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I0Iy2Av'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'markdown' => ['privates', 'cebe\\markdown\\Markdown', 'getMarkdownService', true],
            'user' => ['privates', '.errored..service_locator.I0Iy2Av.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.I0Iy2Av": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'markdown' => 'cebe\\markdown\\Markdown',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
