<?php

namespace ContainerLHUNU3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CkXwAZkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ckXwAZk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ckXwAZk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActivityController::activityInscrit' => ['privates', '.service_locator.I0Iy2Av', 'get_ServiceLocator_I0Iy2AvService', true],
            'App\\Controller\\ActivityController::delete' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController::edit' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController::index' => ['privates', '.service_locator.EuPBtO2', 'get_ServiceLocator_EuPBtO2Service', true],
            'App\\Controller\\ActivityController::indexChild' => ['privates', '.service_locator.EuPBtO2', 'get_ServiceLocator_EuPBtO2Service', true],
            'App\\Controller\\ActivityController::index_myActivity' => ['privates', '.service_locator.EuPBtO2', 'get_ServiceLocator_EuPBtO2Service', true],
            'App\\Controller\\ActivityController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActivityController::show' => ['privates', '.service_locator.FPgZsSk', 'get_ServiceLocator_FPgZsSkService', true],
            'App\\Controller\\ActivityController::showChild' => ['privates', '.service_locator.FPgZsSk', 'get_ServiceLocator_FPgZsSkService', true],
            'App\\Controller\\ActivityController::showMyActivity' => ['privates', '.service_locator.FPgZsSk', 'get_ServiceLocator_FPgZsSkService', true],
            'App\\Controller\\ActivityRegistrationController::edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\admin\\UserAnimatorController::delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\admin\\UserAnimatorController::edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\admin\\UserAnimatorController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\admin\\UserAnimatorController::new' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\admin\\UserAnimatorController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ActivityController:activityInscrit' => ['privates', '.service_locator.I0Iy2Av', 'get_ServiceLocator_I0Iy2AvService', true],
            'App\\Controller\\ActivityController:delete' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController:edit' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController:index' => ['privates', '.service_locator.EuPBtO2', 'get_ServiceLocator_EuPBtO2Service', true],
            'App\\Controller\\ActivityController:indexChild' => ['privates', '.service_locator.EuPBtO2', 'get_ServiceLocator_EuPBtO2Service', true],
            'App\\Controller\\ActivityController:index_myActivity' => ['privates', '.service_locator.EuPBtO2', 'get_ServiceLocator_EuPBtO2Service', true],
            'App\\Controller\\ActivityController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActivityController:show' => ['privates', '.service_locator.FPgZsSk', 'get_ServiceLocator_FPgZsSkService', true],
            'App\\Controller\\ActivityController:showChild' => ['privates', '.service_locator.FPgZsSk', 'get_ServiceLocator_FPgZsSkService', true],
            'App\\Controller\\ActivityController:showMyActivity' => ['privates', '.service_locator.FPgZsSk', 'get_ServiceLocator_FPgZsSkService', true],
            'App\\Controller\\ActivityRegistrationController:edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\admin\\UserAnimatorController:delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\admin\\UserAnimatorController:edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\admin\\UserAnimatorController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\admin\\UserAnimatorController:new' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\admin\\UserAnimatorController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ActivityController::activityInscrit' => '?',
            'App\\Controller\\ActivityController::delete' => '?',
            'App\\Controller\\ActivityController::edit' => '?',
            'App\\Controller\\ActivityController::index' => '?',
            'App\\Controller\\ActivityController::indexChild' => '?',
            'App\\Controller\\ActivityController::index_myActivity' => '?',
            'App\\Controller\\ActivityController::new' => '?',
            'App\\Controller\\ActivityController::show' => '?',
            'App\\Controller\\ActivityController::showChild' => '?',
            'App\\Controller\\ActivityController::showMyActivity' => '?',
            'App\\Controller\\ActivityRegistrationController::edit' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\admin\\UserAnimatorController::delete' => '?',
            'App\\Controller\\admin\\UserAnimatorController::edit' => '?',
            'App\\Controller\\admin\\UserAnimatorController::index' => '?',
            'App\\Controller\\admin\\UserAnimatorController::new' => '?',
            'App\\Controller\\admin\\UserAnimatorController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ActivityController:activityInscrit' => '?',
            'App\\Controller\\ActivityController:delete' => '?',
            'App\\Controller\\ActivityController:edit' => '?',
            'App\\Controller\\ActivityController:index' => '?',
            'App\\Controller\\ActivityController:indexChild' => '?',
            'App\\Controller\\ActivityController:index_myActivity' => '?',
            'App\\Controller\\ActivityController:new' => '?',
            'App\\Controller\\ActivityController:show' => '?',
            'App\\Controller\\ActivityController:showChild' => '?',
            'App\\Controller\\ActivityController:showMyActivity' => '?',
            'App\\Controller\\ActivityRegistrationController:edit' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\admin\\UserAnimatorController:delete' => '?',
            'App\\Controller\\admin\\UserAnimatorController:edit' => '?',
            'App\\Controller\\admin\\UserAnimatorController:index' => '?',
            'App\\Controller\\admin\\UserAnimatorController:new' => '?',
            'App\\Controller\\admin\\UserAnimatorController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
