<?php

namespace ContainerLHUNU3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EuPBtO2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EuPBtO2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EuPBtO2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'markdown' => ['privates', 'cebe\\markdown\\Markdown', 'getMarkdownService', true],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'markdown' => 'cebe\\markdown\\Markdown',
        ]);
    }
}
