<?php

namespace ContainerLHUNU3m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivity2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.adIsG53.App\Entity\Activity' shared service.
     *
     * @return \App\Entity\Activity
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.adIsG53": it references class "App\\Entity\\Activity" but no such service exists.');
    }
}
