<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHUNU3m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHUNU3m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHUNU3m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHUNU3m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHUNU3m\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHUNU3m',
    'container.build_id' => '65c3a958',
    'container.build_time' => 1644879013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHUNU3m');
